#!/bin/bash
read -p "Press any key to move down 100mm." -n1 -s
echo
/var/smith/zed D100000
read -p "Press any key to return to the top." -n1 -s
echo
/var/smith/zed h
read -p "Press any key for full rotation." -n1 -s
echo
/var/smith/zed R360000

