#!/bin/sh
echo 'In shutdown initramfs'

echo 'Moving main storage mount point out of /oldroot'
mount -o move /oldroot/main /main
echo 'Attempting to unmount all filesystems'
umount -a
echo 'Unmounting /oldroot'
umount /oldroot
echo 'Detaching loop device 0'
losetup -d /dev/loop0
echo 'Unmounting /main'
umount /main

# Complete shutdown or restart
# Passed in arg specifies what to do
case $1 in
  poweroff|shutdown|halt)
    "$1" -f
    ;;
  *)
    reboot -f
    ;;
esac
