#!/bin/bash -e

make CONF=CodeCoverage test

gcov -o ./build/CodeCoverage/GNU-Linux-x86 -c *.cpp
lcov --capture --directory ./build/CodeCoverage/GNU-Linux-x86 --output-file coverage.info
genhtml coverage.info --output-directory coverage

