#!/usr/bin/env bash

script_dir=$(cd $(dirname "$0"); pwd)

# Load functions for communicating with board via SSH
source "${script_dir}/remote_communication.sh"

wait_for_connectivity
echo 'Displaying test image'
send_command showtest
