#!/usr/bin/env bash

script_dir=$(cd $(dirname "$0"); pwd)
setup_dir='/root/deploy/setup'

# Load functions for communicating with board via SSH
source "${script_dir}/remote_communication.sh"

# Attempt to reach the board
wait_for_connectivity

echo 'Running motion test'

# Run test
send_command "${setup_dir}/tests/test_motion.sh"
echo 'Done'
