require 'bundler/gem_tasks'

desc 'Deploy'
task deploy: :build do
  gem_file = Dir["#{File.expand_path('../pkg', __FILE__)}/*.gem"].first
  gem_filename = File.basename(gem_file)
  require 'sshkit'
  require 'sshkit/dsl'
  on 'root@192.168.7.2' do
    upload! gem_file, '/root/'
    options = ['install', gem_filename]
    options << '--no-rdoc --no-ri'
    execute :gem, options
  end
end

